- name: common | Ensure Concourse directory exists (windows)
  win_file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ concourseci_bin_dir }}'
    - '{{ concourseci_log_dir }}'

- name: common | Ensure Concourse .ssh dir (windows)
  win_file:
    path: '{{ concourseci_ssh_dir }}'
    state: directory