- name: common | Ensure Concourse group exists (nix)
  group:
    name: '{{ concourseci_group }}'
    state: present

- name: common | Ensure Concourse user exists (nix)
  user:
    home: '{{ concourseci_base_dir }}'
    name: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
    system: yes

- name: common | Ensure Concourse directory exists (nix)
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
    mode: '0750'
  with_items:
    - '{{ concourseci_bin_dir }}'
    - '{{ concourseci_log_dir }}'

- name: common | Ensure Concourse .ssh dir (nix)
  file:
    path: '{{ concourseci_ssh_dir }}'
    state: directory
    mode: 488
    owner: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
