---

- name: Install | Check Concourse archive stat (nix)
  stat:
    path: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
  register: concourseci_binary_file_stat

- name: Install | Ensure Concourse directory exists (nix)
  file:
    path: '{{ concourseci_bin_dir }}/{{ concourseci_binary_package }}'
    state: directory
    owner: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
    mode: '0750'

- name: Install | Download Concourse CI (nix)
  unarchive:
    src: "{{ concourseci_download_url }}"
    remote_src: True
    dest: "{{ concourseci_bin_dir }}/{{ concourseci_binary_package }}"    
    mode: 0755
  become_user: "{{ concourseci_user }}"
  register: concourseci_get
  when: concourseci_binary_file_stat.stat.exists == False
  notify:
   - restart concourse-worker
   - restart concourse-web

- name: Install | Concourse link binary (nix)
  file:
    src: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
    dest: "{{ concourseci_bin_dir }}/concourse"
    state: "link"
  notify:
   - restart concourse-worker
   - restart concourse-web
