---

- name: Install | Check Concourse archive stat (windows)
  win_stat:
    path: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
  register: concourseci_binary_file_stat

- name: Install | Download Concourse CI (windows)
  win_get_url:
    url: "{{ concourseci_download_url }}"
    dest: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
  register: concourseci_get
  when: concourseci_binary_file_stat.stat.exists == False
  notify:
   - restart concourse-worker
   - restart concourse-web