---

- name: Install | Check Concourse archive stat (nix)
  stat:
    path: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
  register: concourseci_binary_file_stat

- name: Install | Download Concourse CI (nix)
  get_url:
    url: "{{ concourseci_download_url }}"
    dest: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
    mode: 0755
  become_user: "{{ concourseci_user }}"
  register: concourseci_get
  when: concourseci_binary_file_stat.stat.exists == False
  notify:
   - restart concourse-worker
   - restart concourse-web

- name: Install | Concourse link binary (nix)
  file:
    src: "{{ concourseci_bin_dir }}/{{ concourseci_binary_file }}"
    dest: "{{ concourseci_bin_dir }}/concourse"
    state: "link"
  notify:
   - restart concourse-worker
   - restart concourse-web
