- name: worker | Concourse worker start script (windows)
  template:
    src: "concourse-worker-powershell.j2"
    dest: "{{ concourseci_bin_dir }}/concourse-worker.ps1"
  notify:
   - restart concourse-worker

- name: worker | Copy session public key (windows)
  win_copy:
    content: "{{ concourseci_key_session_public }}"
    dest: "{{ concourse_worker_options_combined['CONCOURSE_SESSION_SIGNING_KEY'] }}.pub"
  notify:
   - restart concourse-worker

- name: worker | Copy tsa public key (windows)
  win_copy:
    content: "{{ concourseci_key_tsa_public }}"
    dest: "{{ concourse_worker_options_combined['CONCOURSE_TSA_HOST_KEY'] }}.pub"
  notify:
   - restart concourse-worker

- name: worker | Copy worker public key (windows)
  win_copy:
    content: "{{ concourseci_key_worker_public }}"
    dest: "{{ concourse_worker_options_combined['CONCOURSE_TSA_WORKER_PRIVATE_KEY'] }}.pub"

- name: worker | Copy worker private key (windows)
  win_copy:
    content: "{{ concourseci_key_worker_private }}"
    dest: "{{ concourse_worker_options_combined['CONCOURSE_TSA_WORKER_PRIVATE_KEY'] }}"
  no_log: True
  notify:
    - restart concourse-worker

- name: Worker | Ensure NSSM is installed
  win_chocolatey: name=nssm

- name: Worker | Ensure Concourse worker is running and Starts on boot (windows)
  win_nssm:
    name: concourse-worker
    application: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
    stdout_file: "{{ concourseci_log_worker }}"
    stderr_file: "{{ concourseci_log_worker }}"
    app_parameters_free_form: "{{ concourseci_bin_dir }}/concourse-worker.ps1"